### ISSUE TITLE
Need policy on sharing devices between FW and OS

### ISSUE THREAD

**Issue by glikely** [ARM-software/ebbr#1]
EBBR needs to comment on whether it is okay for firmware to access devices at runtime (ie. via a Runtime Services call, or via SecureWorld).

Typically there should be no sharing of devices at all. A device's register interface should be either entirely owned by firmware or entirely owned by the OS.

**Comment by wmamills** [comment]
This one can be assigned to me

**Comment by glikely** [comment]
@wmamills You should have received an invitation to collaborate from GitHub. You'll need to accept that before I can assign the issue.

**Comment by wmamills** [comment]
@glikely I have now.  You assigned the ones I wrote to me so I thought I was grandfathered in somehow.  These permissions are a bit subtle.

**Comment by glikely** [comment]
@wmamills Yup, it's a bit weird. I can assign any issue to the person who raised it, but can only assign others if they are part of the project.
