### ISSUE TITLE
Document how to certify platform supports EBBR 

### ISSUE THREAD

**Issue by Uditkr** [ARM-software/ebbr#10]
Purpose of this ticket, to document, some sort of compliance test to declare that platform supports EBBR. 

Is UEFI SCT is enough for this ?

**Comment by glikely** [comment]
Closing this issue. The issue remains unresolved, but it is too generic to be useful. Instead, new issues should be added for specific testing requirements when the test infrastructure becomes mature. For instance, there is activity around adding UEFI tests to the U-Boot CI loop and also getting SCT to run on U-Boot. However, until those activities have concrete outputs, there isn't anything we can do on EBBR.
