### ISSUE TITLE
Document hardware need (if any)

### ISSUE THREAD

**Issue by Uditkr** [ARM-software/ebbr#11]
Draft EBBR does not mention any hardware requirement expect ARM CPU architecture.
Purpose of this ticket to mention hardware need (if any) like interrupt controllers, timers etc. 
IMO, a small note in this document should be ok .

**Comment by glikely** [comment]
Closing this issue. There are no hardware requirements in EBBR yet, and it is unclear if we need to add any. If and when specific requirements become mandatory, then issues should be raised to add that specific requirement to EBBR.
