### ISSUE TITLE
Document scope of level 0, level 1, etc.

### ISSUE THREAD

**Issue by daniel-thompson** [ARM-software/ebbr#12]
A roadmap document to describe which features we hope to target for what level would be very useful... especially to keep us focused on getting level 0 out of the door!

**Comment by daniel-thompson** [comment]
@glikely: I can't assign myself this issue ;-)

**Comment by glikely** [comment]
@daniel-thompson Still trying to figure out how the issues permissions work

**Comment by glikely** [comment]
Decision on not split EBBR releases into level sections. (at least not yet). We're going to maintain a todo list instead for now.

May be useful to revisit when we have hardware of varying capability
