### ISSUE TITLE
Add Intro section that gives some (non-binding) context

### ISSUE THREAD

**Issue by wmamills** [ARM-software/ebbr#13]
I think we need an intro section that shows what our approach is and why this is different than the server requirements.

Examples: (not these words)
* Spec is implementation independent but is defined so it can be satisfied by Tianocore/EDK2 or u-boot
* DeviceTree or ACPI
* "Embedded" platforms may not have RTC or require OS and firmware to share a single storage medium

We should also discuss the "levels" of EBBR and how we approach that.

**Comment by glikely** [comment]
I've done a bit of rework to the Scope section that talks about how EBBR differs from SBBR (I'll post the patch shortly), but a lot more can be written.
