### ISSUE TITLE
Add Appendix for example use cases

### ISSUE THREAD

**Issue by wmamills** [ARM-software/ebbr#18]
Add an appendix that has example use cases to show the value and illustrate operation.
These are examples and are not requirements.
Will reference example platforms to show how use case can be achieved

Include such things as:
* Installer removable media (or net boot media) installing to platform
* Board specific media that prompts user for selection of possible OS'es to install (like RPi Noob)
* OS Live disk image
* Board specific recovery image (include to show that it is not bound to EBBR rules)

**Comment by glikely** [comment]
Anyone want to take this on? If not then I'll close the issue as nobody cares enough.
