### ISSUE TITLE
Create standard path layout for system firmware partitions

### ISSUE THREAD

**Issue by glikely** [ARM-software/ebbr#19]
To facilitate storing system firmware for multiple SoCs on the same block device, we need a standard path layout for where to store the firmware files. Each Vendor/SoC should get its own subdirectory.

Having a path standard is needed for both the separate system firmware partition scenario, and the firmware-files-in-ESP scenario

**Comment by robherring** [comment]
Perhaps the subdirectory names should be (or include) registered DT vendor prefixes.

**Comment by glikely** [comment]
That's a good idea. I've added that to the draft I'm working on.
