### ISSUE TITLE
DT stability needs to get annotated

### ISSUE THREAD

**Issue by agraf** [ARM-software/ebbr#23]
We should require device trees to be backwards compatible. The easiest way to ensure this is to have a tag in the DT that tells reviewers and users of the DT that they can expect backwards compatibility of the device tree.

This tag and requirement of the tag needs to get documented in EBBR. Without the tag, EBBR compliance won't exist.

The tag also needs to get an official binding in the Linux DT binding documents.

**Comment by glikely** [comment]
We don't have a clear way forward on this one. I'm closing the issue because we cannot do anything on EBBR until we've got consensus amongst the DT devs.
