### ISSUE TITLE
Support for UEFI secure boot

### ISSUE THREAD

**Issue by nullr0ute** [ARM-software/ebbr#30]
We should specify and have in the reference implementation support for UEFI secure boot.
There would need to be means to enroll keys etc.

**Comment by glikely** [comment]
Now that there is secure boot development activity going on aside from EBBR (ie. Linaro LEDGE, within Arm, and a few other places), I don't think this needs to be tracked here. Once secure boot support is mainlined in U-Boot/TF-A/OP-TEE then a new issue should be raised to add secure boot requirements/recommendations to EBBR.
