### ISSUE TITLE
Support for UEFI Capule updates for firmware updates

### ISSUE THREAD

**Issue by nullr0ute** [ARM-software/ebbr#32]
Support for being able to update the firmware using industry standard UEFI capsule from the OS using tools such as fwupdate (https://github.com/rhboot/fwupdate)

**Comment by nullr0ute** [comment]
Also needs to publish ESRT tables

**Comment by glikely** [comment]
Do we have infrastructure in U-Boot yet to perform firmware updates via Capsule Update? If not, then I'll close this issue until we do. Linaro LEDGE may very well take on this work item.

Once the support is in mainline, we can add the requirement to EBBR
