### ISSUE TITLE
GOP/BGRT Support

### ISSUE THREAD

**Issue by nullr0ute** [ARM-software/ebbr#33]
If graphics is supported the BGRT should to be supported

**Comment by glikely** [comment]
What is the state of GOP/BGRT support in U-Boot?

I'll leave this issue open for now since it isn't being tracked anywhere else (unlike the secure boot stuff which is being tracked within Linaro LEDGE)

**Comment by agraf** [comment]
U-Boot supports GOP, but does not expose a BGRT table.
