### ISSUE TITLE
Optional support of TPM2 and EFI TPM2 protocol

### ISSUE THREAD

**Issue by nullr0ute** [ARM-software/ebbr#34]
For attested boot we should support the EFI TPM2 protocol. It shouldn't be a hard requirement but would be useful for IoT devices and other related devices.

**Comment by glikely** [comment]
Are we ready to add this as a requirement? Is there any support in U-Boot? If not, then I'd like to close this issue until there is a viable way to implement it.

**Comment by nullr0ute** [comment]
Wouldn't we be better off tagging it future and leaving it open for easier tracking?
