### ISSUE TITLE
Support HTTP boot

### ISSUE THREAD

**Issue by nullr0ute** [ARM-software/ebbr#35]
Section 24.7 HTTP boot of version 2.7 of the UEFI spec. Useful for provisioning of devices.

**Comment by glikely** [comment]
Will this change the content of EBBR, or should it be a tracking item on U-Boot development?

**Comment by daniel-thompson** [comment]
Is this a candidate for a conditional recommendation: if the platform has on-board ethernet then implementations should provide the HTTP boot protocol ?

(personally I'm not 100% convinced... arguably it is an implementation quality issue rather than something to standardize)

**Comment by robherring** [comment]
There's currently a v12 patch series for u-boot adding TCP and http. 

https://patchwork.ozlabs.org/patch/934007/

**Comment by nullr0ute** [comment]
I think it should be branded as nice to have or similar, but given U-Boot is the reference implementation and not the standard I still believe it to be in scope of the standard.

**Comment by glikely** [comment]
Any updates on the state of U-Boot support for UEFI HTTP boot?

Even if it is implemented, I'm less convinced that it should be specified in EBBR. The UEFI spec should be sufficient.
