### ISSUE TITLE
Provide a positive list of requirements

### ISSUE THREAD

**Issue by xypron** [ARM-software/ebbr#60]
In the EBBR we require to implement everything that is in chapter "2.6 Requirements" of the UEFI spec if it is not explicitly excluded in the EBBR.

* This requires scope that is far too big for the embedded use case.
* This is not easily testable because of the many cross references in the UEFI spec.
* It is a scope that U-Boot will never implement.

We should return to a positive list of requirements.

Here are examples of what should be discussed:

* support for EFI_LOAD_FILE_PROTOCOL  and EFI_LOAD_FILE2_PROTOCOL in LoadImage()
* support for EFI_PLATFORM_DRIVER_OVERRIDE_PROTOCOL and  EFI_DRIVER_FAMILY_OVERRIDE_PROTOCOL in ConnectController()
* supported nodes in EFI_DEVICE_PATH_TO_TEXT_PROTOCOL

Especially for protocols to be implemented we need a list identifying the once really needed to be implemented. Protocols required by chapter 2.6 and not implemented in U-Boot include for example:

* EFI_DISK_IO_PROTOCOL
* EFI_NETWORK_INTERFACE_IDENTIFIER_PROTOCOL 
* EFI_EDID_DISCOVERED_PROTOCOL
* EFI_EDID_ACTIVE_PROTOCOL

**Comment by glikely** [comment]
The RNG protocol requirement should also be reflected here.
