### ISSUE TITLE
Exclude EFI_DECOMPRESS_PROTOCOL

### ISSUE THREAD

**Issue by xypron** [ARM-software/ebbr#61]
The UEFI specifiction does not describe the compression algorithm used for the EFI_DECOMPRESS_PROTOCOL. Only sample code is provided. So it is impossible to create an independent implementation.

BaseTools/Source/C/Common/EfiCompress.c has a BSD-2-Clause-Patent license. It is unknown if an independent implementation of the compression protocol would infringe Intel's patents.

We should exclude the requirement to implement the EFI_DECOMPRESS_PROTOCOL from the EBBR specification.

**Comment by daniel-thompson** [comment]
> The UEFI specifiction does not describe the compression algorithm used
> for the EFI_DECOMPRESS_PROTOCOL. Only sample code is provided.

Can you explain what you mean by only sample code is provided? There is sample code in the appendix but I count around 12 pages describing the compression/decompression algorithm and these have been included in the spec since at least 2006.

**Comment by glikely** [comment]
Agree, this protocol can probably be dropped from EBBR
