### ISSUE TITLE
Update EBBR to use BBR instead of SBBR

### ISSUE THREAD

**Issue by glikely** [ARM-software/ebbr#62]
Arm has refactored the SBBR document to include a generic part (BBR, Base Boot Requirements) and segment specific recepies (e.g., SBBR, Server Base Boot Requirements). The BBR structure makes it easier for EBBR to draw from language already in the BBR spec without duplicating language from SBBR.

EBBR should be refactored to refer to the generic portions of BBR, particularly in regard to exception level handling and secure world interfaces (PSCI, etc).

BBR Spec: https://developer.arm.com/documentation/den0044/latest

**Comment by hrw** [comment]
Section 3.2 of EBBR allows PSCI or spin tables (with note that spin tables will be gone from spec). 

BBR requires PSCI.
