### ISSUE TITLE
Globally Defined Variables

### ISSUE THREAD

**Issue by xypron** [ARM-software/ebbr#64]
Chapter "3.3 Globally Defined Variable" of the UEFI spec defines possible global variables.

The chapter is not referenced in the EBBR.

We need a definition which variables must exist on an EBBR compliant device and which must be supported.

**Comment by glikely** [comment]
I imagine EBBR wouldn't change the definition of global variables, correct? A section could be added for "Required Global Variables". What variables do you see as necessary?

the obvious:
- Boot####
- BootCurrent
- BootNext
- BootOrder
- BootOptionSupport

**Comment by glikely** [comment]
Hmmm... maybe not that last one; BootOptionSupport would be trivial to implement, but how is it actually used?
