### ISSUE TITLE
Add reference to EFI_TCG2_PROTOCOL

### ISSUE THREAD

**Issue by xypron** [ARM-software/ebbr#65]
The [TCG EFI Protocol Specification Family 2.0 Level 00 Revision 00.13 March 30, 2016](https://trustedcomputinggroup.org/wp-content/uploads/EFI-Protocol-Specification-rev13-160330final.pdf) defines the EFI_TCG2_PROTOCOL. We should add this optional protocol as a reference in the EBBR specification.

**Comment by glikely** [comment]
Can you provide some proposed text?
