### ISSUE TITLE
Add implementors notes for U-Boot platforms

### ISSUE THREAD

**Issue by glikely** [ARM-software/ebbr#7]
The U-Boot project supports a subset of the UEFI specification, but EBBR compliance also depends on how U-Boot is configured. Add an appendix or supplemental document detailing how to configure U-Boot to be EBBR compliant.

**Comment by igoropaniuk** [comment]
This is already done in U-boot documentation:

http://git.denx.de/?p=u-boot.git;a=blob;f=doc/README.uefi;h=1d1039a6ae75bc402889ebc8f2f6f79732a020aa;hb=HEAD
