### ISSUE TITLE
Uniqueness of device paths

### ISSUE THREAD

**Issue by xypron** [ARM-software/ebbr#72]
Device paths are used to identify devices and therefore should be unique.

The UEFI spec requires that InstallMultipleProtocolInterfaces() checks that it does not installing a duplicate device paths. It has to return an EFI_ALREADY_STARTED in this case.

For InstallProtocolInterface() such a requirement is missing. So we could end up creating conflicts.

The UEFI spec should be amended.

**Comment by glikely** [comment]
Sounds like something that should be fed back to the USWG instead of put
into EBBR.

g.

**Comment by glikely** [comment]
Is this something we need to discuss at the biweekly on Monday?

**Comment by xypron** [comment]
On 2/12/21 8:01 PM, Grant Likely wrote:
> Is this something we need to discuss at the biweekly on Monday?
>

We should discuss how we can carry such observations to the right
UEFI.org bodies.

**Comment by glikely** [comment]
Closed as it is a UEFI USWG topic
