### ISSUE TITLE
v2.0.1 is not updated in EBBR webpage

### ISSUE THREAD

**Issue by atishp04** [ARM-software/ebbr#88]
EBBR github repo as v2.0.1 release tag. However, it is not updated in the EBBR webpage (https://arm-software.github.io/ebbr/).
It still lists v2.0.0 as the latest version. It leads to the confusion about the latest spec version. 

Can it be updated to include v2.0.1 to avoid the confusion ?

**Comment by glikely** [comment]
The webpages used to be generated by TravisCI, but that CI loop no longer works. I needed to switch the repo to using Github Actions which is now done. Still to be fixed is actually deploying the generated HTML files. I'll see about getting that done shortly.

**Comment by stappersg** [comment]
FWIW:  I felt the need to make a reference to #92  ...
