### ISSUE TITLE
RISC-V: /chosen/boot-hartid is deprecated in UEFI 2.10

### ISSUE THREAD

**Issue by xypron** [ARM-software/ebbr#97]
@avpatel @atishp04 

UEFI specification 2.10 has deprecated the boot-hartid value in the /chosen node and requires the RISCV_EFI_BOOT_PROTOCOL instead.

I would prefer to simply drop the corresponding requirement in chapter3-secureworld.rst.

**Comment by vstehle** [comment]
Dropped in https://github.com/ARM-software/ebbr/commit/f2e2e5eb54f04121bdc11b49b2450fc3a9dd456e
