### ISSUE TITLE
PSCI spec link is outdated

### ISSUE THREAD

**Issue by samerhaj** [ARM-software/ebbr#98]
The link to the PSCI specification in section 5. Bibliography is outdated:

The current link https://static.docs.arm.com/den0022/c/DEN0022C_Power_State_Coordination_Interface.pdf is no longer working.

The link should be updated to: https://developer.arm.com/documentation/den0022/c/ , or 
https://developer.arm.com/documentation/den0022/latest  if pointing to the latest revision

**Comment by vstehle** [comment]
Fixed in https://github.com/ARM-software/ebbr/commit/95fd1ba8cb2230aa984f4b2783144e839371b3cf
